before_install:
  - type swiftlint >/dev/null 2>&1 || (brew update && brew install swiftlint) # Install swiftlint if it's not installed
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18.1/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - carthage version # Print version for debugging purposes
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - travis_retry make bootstrap
        - make test
      env: JOB=CI_BUILD_TEST
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - travis_retry make package
      env: JOB=CI_BUILD_PACKAGE
deploy:
  provider: releases
  api_key:
    secure: Xii7r5MPBRCaUHwU4PX1bXAuDfsa/Evlh7/qNmcTNCHQbPckduQSyXIEiPn+dOYAL0qDTe71a+8DISreOPZ4n0R6NFcQfvwpLo0j1fnVpC0MtaBQC+s94GwR2eoJWBCmy63f1g9NEcyksFtdhdLOlmjzdOwVDLn3NKopOtdeJ/J9BwgROAa1e4JnyeBTcMnG/22hYOwoLxfSWQwHyRULGvonqImcqQUhNds8S2sa4ItUrxkVNLRYIxZBkuz3TjQHoYwB8cZbp5oe8hVTrXrGejid0O++/z25Wen1vjBctObki851/jSJ4ARla6qFmdWJGsfOFkEoC2YlSox5+9cwOwO6jXjYNFrRVhqNG2LmSCj24DlcgKcPQ9BHR3QRgqguFSfH2bCqK0Rw8umhv1EhdcOZHcCapU/VLieZEE2yiqZqW9Xv0WikfBeYnXBCquGmpPwQrn/iNp+siWcM9dS2W6kvye7BP4uj/KJMVrzGcyd4FFjJemkDd3klkRp0TxLlC53uSp6rPu3cua6jZJ1DOFVoge7WzHbhp8OG9SCFaoavPdednWmI2Qwk6dQDHRUtPhCge5ug7zYYozhE2OdLvjCQdjgibbFDCX1RaYLgR9PuCSnj1RPf88UBSPTuh1XU9orMZVU7gTp+24qVRrWQX3QeoX3GeaNk9aO/RZq8Ea4=
  file: Yomu.pkg
  skip_cleanup: true
  on:
    tags: true
    repo: sendyhalim/Yomu
    condition: $JOB = CI_BUILD_PACKAGE
